package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

/**
 * ExerciesDetail generated by hbm2java
 */
public class ExerciseDetail implements java.io.Serializable {

	private Integer id;
	private Exercise exercise;
	private Question question;
	private Integer answer;

	public ExerciseDetail() {
	}

	public ExerciseDetail(Exercise exercise, Question question, Integer answer) {
		super();
		this.exercise = exercise;
		this.question = question;
		this.answer = answer;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Exercise getExercise() {
		return exercise;
	}

	public void setExercise(Exercise exercise) {
		this.exercise = exercise;
	}

	public Question getQuestion() {
		return question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Integer getAnswer() {
		return answer;
	}

	public void setAnswer(Integer answer) {
		this.answer = answer;
	}
	
}
