package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * Exercies generated by hbm2java
 */
public class Exercise implements java.io.Serializable {

	private Integer id;
	private Subject subject;
	private User user;
	private String exerciseName;
	private String exerciseImg;
	private Integer totalQuestion;
	private Timestamp createTime;
	private Boolean submitted;
	private Boolean deleted;
	private List<ExerciseDetail> exerciseDetails = new ArrayList<ExerciseDetail>();

	public Exercise() {
	}

	public Exercise(Subject subject, User user, String exerciseName, String exerciseImg, Integer totalQuestion,
			Timestamp createTime, Boolean submitted, Boolean deleted, List<ExerciseDetail> exerciseDetails) {
		super();
		this.subject = subject;
		this.user = user;
		this.exerciseName = exerciseName;
		this.exerciseImg = exerciseImg;
		this.totalQuestion = totalQuestion;
		this.createTime = createTime;
		this.submitted = submitted;
		this.deleted = deleted;
		this.exerciseDetails = exerciseDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getExerciseName() {
		return this.exerciseName;
	}

	public void setExerciseName(String exerciesName) {
		this.exerciseName = exerciseName;
	}

	public String getExerciseImg() {
		return this.exerciseImg;
	}

	public void setExerciseImg(String exerciesImg) {
		this.exerciseImg = exerciseImg;
	}

	public Integer getTotalQuestion() {
		return this.totalQuestion;
	}

	public void setTotalQuestion(Integer totalQuestion) {
		this.totalQuestion = totalQuestion;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public List<ExerciseDetail> getExerciseDetails() {
		return exerciseDetails;
	}

	public void setExerciseDetails(List<ExerciseDetail> exerciseDetails) {
		this.exerciseDetails = exerciseDetails;
	}

	public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Boolean getSubmitted() {
		return submitted;
	}

	public void setSubmitted(Boolean submitted) {
		this.submitted = submitted;
	}
	
}
