package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

/**
 * GoogleAccounts generated by hbm2java
 */
public class GoogleAccount implements java.io.Serializable {

	private int usersId;
	private User user;
	private String googleId;
	private Boolean deleted;

	public GoogleAccount() {
	}
	
	public GoogleAccount(int usersId, String googleId) {
		this.usersId= usersId;
		this.googleId= googleId;
	}

	public GoogleAccount(User user, String googleId) {
		this.user = user;
		this.googleId = googleId;
	}

	public GoogleAccount(User user, String googleId, Boolean deleted) {
		this.user = user;
		this.googleId = googleId;
		this.deleted = deleted;
	}

	public int getUsersId() {
		return this.usersId;
	}

	public void setUsersId(int usersId) {
		this.usersId = usersId;
	}

	public String getGoogleId() {
		return this.googleId;
	}

	public void setGoogleId(String googleId) {
		this.googleId = googleId;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
