package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Levels generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean deleted;
	private List<Question> questions;

	public Level() {
	}

	public Level(String name, Boolean deleted, List<Question> questions) {
		this.name = name;
		this.deleted = deleted;
		this.questions = questions;
	}
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public List<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

}
