package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

/**
 * PostTag generated by hbm2java
 */
public class PostTag implements java.io.Serializable {

	private Integer id;
	private Post post;
	private Tag tag;

	public PostTag() {
	}

	public PostTag(Post post, Tag tag) {
		this.post = post;
		this.tag = tag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public Tag getTag() {
		return tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
