package vn.framgia.model;
// Generated Dec 7, 2018 9:59:06 AM by Hibernate Tools 5.3.6.Final

import java.util.List;

/**
 * Subjects generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private Integer id;
	private String subjectName;
	private Boolean deleted;
	private List<Question> questions;
	private List<Exercise> exercises;

	public Subject() {
	}

	public Subject(String subjectName, Boolean deleted, List<Question> questions, List<Exercise> exercises) {
		this.subjectName = subjectName;
		this.deleted = deleted;
		this.questions = questions;
		this.exercises = exercises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public List<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	public List<Exercise> getExercises() {
		return this.exercises;
	}

	public void setExercises(List<Exercise> exercises) {
		this.exercises = exercises;
	}

}
